locale: "en-US"
title: Jayvee Velayo
url: "https://jayveevelayo.com"
baseurl: ""
google_analytics_key: "UA-126192862-1"

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Jayvee Velayo. Check out his new projects right here!

# Author details for the jekyll-seo-tag gem
author:
  name: Jayvee Velayo
  email: jadon.velayo@gmail.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Jayvee Velayo
  links:
    - https://github.com/jayvelayo

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
